### ISSUE TITLE
Well Done!

### ISSUE THREAD

**Issue by marcfielding1** [AndersDJohnson/fetch-paginate#25]
This isn't a issue really, I've just written some code to deal with paginated API's and it's a ballache, so then I thought I'm just knock up and NPM library so I never have to do this again, you beat me to it lol.

Looks very useful - I'm going to have a play with it against some WooCommerce API's and some other bits, I take it you're open to contributions providing they're up to scratch?

**Comment by AndersDJohnson** [comment]
@marcfielding1 🙇 Thank you very much! Please help spread the good word. 📣 Very open to contributions! I hope you are using the latest 6.x version with the cleanest API. In fact, I just released `6.1.0` which supports a new async iterators (`for await ... of`) API too. Check it out and let me know what you think!
