### ISSUE TITLE
core-js errors in dist - move to dependencies?

### ISSUE THREAD

**Issue by haywirez** [AndersDJohnson/fetch-paginate#36]
Getting a bunch of core-js related errors in webpack after including:

```
ERROR in ./node_modules/fetch-paginate/dist/main.js
Module not found: Error: Can't resolve 'core-js/modules/es.array.concat'
Module not found: Error: Can't resolve 'core-js/modules/es.array.iterator'
Module not found: Error: Can't resolve 'core-js/modules/es.array.map'
Module not found: Error: Can't resolve 'core-js/modules/es.array.reduce'
```

Perhaps some babel dependencies are missing?

**Comment by AndersDJohnson** [comment]
Hi @haywirez thanks for reporting. I'll have to try to repro. I do have `core-js@3` in the deps, are you using `babel-preset-env` with `core-js@2` configured? Would you be able to share your package.json and Babel and Webpack config?

**Comment by haywirez** [comment]
Sorry, I think I forgot a crucial piece - I'm consuming the dist version in my own repository. In theory, I shouldn't need any extra dependencies.

**Comment by AndersDJohnson** [comment]
> Sorry, I think I forgot a crucial piece - I'm consuming the dist version in my own repository. In theory, I shouldn't need any extra dependencies.

@haywirez Unfortunately we do require `core-js` as a dependency today, though if we prefer perhaps we could look at bundling those dependencies into the dist. Thoughts?
