### ISSUE TITLE
Cannot use with node-fetch

### ISSUE THREAD

**Issue by aguiraf** [AndersDJohnson/fetch-paginate#61]
Hi, I'm working in node with CommonJS require;
```
const fetch = require('node-fetch')
const fetchPaginate = require('fetch-paginate')

const { items } =  fetchPaginate("https://api.example.com/foo")
```
and keep getting 
```
ReferenceError: fetch is not defined
    at S (/home/raf/git/pvova-fetch-paginate/node_modules/fetch-paginate/dist/main.js:1:3296)
    at /home/raf/git/pvova-fetch-paginate/node_modules/fetch-paginate/dist/main.js:1:4179
    ...
```

It only works with 
```
require('cross-fetch/polyfill')
```

any hint? Thank you very much

**Comment by AndersDJohnson** [comment]
@aguiraf Thanks for using this library! We expect `fetch` to be available in the global namespace, as `cross-fetch/polyfill` provides. With `node-fetch`, you should be able to do this manually like:
```js
const fetch = require('node-fetch');

global.fetch = fetch;

// ...
```

Let me know if that works for you, and perhaps we can update the docs to make this clear.

**Comment by aguiraf** [comment]
Hi Anders,
tjank you for replying and sorry for the late response;
It worked perfectly!
