### ISSUE TITLE
Missing Fetch Options?

### ISSUE THREAD

**Issue by skydiablo** [AndersDJohnson/fetch-paginate#70]
Hi, my JS knowledge is very poor ;) i just want to use your lib in a simple website, so i add this script via HTML head:

>   <script src='https://unpkg.com/fetch-paginate@3.0.1/bundle.js'></script>

and call it like this:

```JS

const defaultFetchOptions = {
  headers: {
    'X-AUTH-TOKEN': 'XXXXXXX'
   }
};

fetchPaginate.default('https://foo.bar/api?param_x=40', {
  fetchOptions: defaultFetchOptions,
  getItems: function (body) {
    return body.rows
  },
  params: true,
  page: 0,
})
.then(function (data) {
  ...
}
```

in my developer toolbar i can see the correct request with param "page=0" but the fetch header option `X-AUTH-TOKEN` is missing :( what i doing wrong?

volker.

**Comment by AndersDJohnson** [comment]
@skydiablo Interesting. I see you're using a pretty old version (`3.0.1`) - you might try the latest (`6.1.0`).

I just created this JSFiddle to prove it works: https://jsfiddle.net/e1qn42fg/17/

I also just added some unit tests that prove it works in Node (https://github.com/AndersDJohnson/fetch-paginate/pull/72).
